#!/bin/sh

[ -x /usr/bin/fb-test ] || exit 0
[ -f /sys/class/graphics/fb2/blank ] || exit 0

case "$1" in
  start)
	echo "0" > /sys/class/graphics/fb2/blank
	/usr/bin/fb-test -f 2
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
